import { useState } from 'react';
import type { TacticalEntry, TacticalLineupPlayer } from '../../lib/sportsStatistics';
import PlayerAvatar from './PlayerAvatar';
import { displayName, initials, playerPhoto, type StatisticsViewProps } from './types';

const percentage = (value: number | null) => value === null ? 'Sin datos' : `${Math.round(value * 100)}%`;

export default function TacticsView({ stats, players, equipoId }: StatisticsViewProps) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const toggle = (system: string) => setExpanded((current) => { const next = new Set(current); if (next.has(system)) next.delete(system); else next.add(system); return next; });
  return <section className="statistics-section">{!stats.tactical.registeredSystems.length ? <div className="statistics-empty"><strong>No hay sistemas registrados para estos filtros</strong><p>Los partidos finalizados todavía no tienen un registro histórico de formación disponible.</p></div> : <div className="statistics-tactics-list">{stats.tactical.registeredSystems.map((system) => <TacticalCard key={system.system} entry={system} expanded={expanded.has(system.system)} onToggle={() => toggle(system.system)} players={players} equipoId={equipoId} canCompare={stats.evidence.canCompare} />)}</div>}</section>;
}

function TacticalCard({ entry, expanded, onToggle, players, equipoId, canCompare }: { entry: TacticalEntry; expanded: boolean; onToggle: () => void; players: StatisticsViewProps['players']; equipoId: number; canCompare: boolean }) {
  return <article className="statistics-tactical-card"><button type="button" className="statistics-tactical-toggle" onClick={onToggle} aria-expanded={expanded}><span><strong>{entry.system}</strong><small>{entry.matches} registros · {percentage(entry.usageRate)} de uso</small></span><b aria-hidden="true">{expanded ? '−' : '+'}</b></button>{expanded && <div className="statistics-tactical-content">{canCompare ? <div className="statistics-tactical-metrics"><span>Victorias <b>{entry.wins}</b></span><span>Empates <b>{entry.draws}</b></span><span>Derrotas <b>{entry.losses}</b></span><span>GF / GC <b>{entry.goalsFor} / {entry.goalsAgainst}</b></span></div> : <p className="statistics-unknown">La comparación de resultados se habilita con 5 partidos finalizados; se conserva el uso registrado.</p>}{entry.latestSnapshot ? <><p className="statistics-snapshot-meta">Último partido: {entry.latestSnapshot.formationName} · vs {entry.latestSnapshot.rival} · {entry.latestSnapshot.date}{entry.latestSnapshot.time ? ` · ${entry.latestSnapshot.time}` : ''}</p><div className="statistics-tactical-lineup-layout"><FormationThumbnail snapshot={entry.latestSnapshot} playersList={players} equipoId={equipoId} /><div className="statistics-lineups"><LineupGroup title="Titulares" players={entry.latestSnapshot.starters} playersList={players} equipoId={equipoId} /><LineupGroup title="Suplentes" players={entry.latestSnapshot.substitutes} playersList={players} equipoId={equipoId} variant="substitutes" /></div></div></> : <p className="statistics-unknown">No hay una formación histórica de jugadores para este sistema.</p>}</div>}</article>;
}

function FormationThumbnail({ snapshot, playersList, equipoId }: { snapshot: NonNullable<TacticalEntry['latestSnapshot']>; playersList: StatisticsViewProps['players']; equipoId: number }) {
  return <div className="statistics-formation-thumbnail" aria-label={`Formación ${snapshot.formationName}`}><div className="statistics-formation-pitch"><svg className="statistics-pitch-markings" viewBox="0 0 100 145" preserveAspectRatio="none" aria-hidden="true"><g className="statistics-pitch-lines"><rect x="1.25" y="1.25" width="97.5" height="142.5" /><path d="M1.25 72.5h97.5M20 1.25v20h60v-20M35 1.25v8h30v-8M20 143.75v-20h60v20M35 143.75v8h30v-8" /><circle cx="50" cy="72.5" r="12" /><circle className="statistics-pitch-spot" cx="50" cy="72.5" r=".8" /><circle className="statistics-pitch-spot" cx="50" cy="15" r=".8" /><circle className="statistics-pitch-spot" cx="50" cy="130" r=".8" /><path d="M40.7 21.25a10.5 10.5 0 0 0 18.6 0M40.7 123.75a10.5 10.5 0 0 1 18.6 0" /><path d="M1.25 5.5a4.25 4.25 0 0 1 4.25-4.25M98.75 5.5A4.25 4.25 0 0 0 94.5 1.25M1.25 139.5a4.25 4.25 0 0 0 4.25 4.25M98.75 139.5a4.25 4.25 0 0 1-4.25 4.25" /><path className="statistics-pitch-goal" d="M43 1.25v3.75h14v-3.75M43 143.75v-3.75h14v3.75" /></g></svg>{snapshot.starters.map((player) => { const name = displayName(player.displayName, player.playerId, playersList, equipoId); const marker = player.dorsal || initials(name); return <span key={player.playerId} role="img" className="statistics-formation-marker" title={name} aria-label={`${name}, ${player.dorsal ? `dorsal ${player.dorsal}` : 'sin dorsal'}`} style={{ left: `${player.x}%`, top: `${player.y}%`, '--marker-main': snapshot.camiseta.principal, '--marker-border': snapshot.camiseta.secundaria, '--marker-text': snapshot.camiseta.texto } as React.CSSProperties}><span>{marker}</span></span>; })}</div></div>;
}

function LineupGroup({ title, players, playersList, equipoId, variant = 'default' }: { title: string; players: TacticalLineupPlayer[]; playersList: StatisticsViewProps['players']; equipoId: number; variant?: 'default' | 'substitutes' }) {
  return <div className={`statistics-lineup${variant === 'substitutes' ? ' statistics-lineup--substitutes' : ''}`}><h2>{title}</h2>{players.length ? <div className="statistics-lineup-list">{players.map((player) => { const name = displayName(player.displayName, player.playerId, playersList, equipoId); return <div key={player.playerId}><PlayerAvatar name={name} photo={playerPhoto(player.playerId, player.foto, playersList, equipoId)} /><span><strong>{name}</strong><small>{player.dorsal ? `Dorsal ${player.dorsal}` : 'Dorsal no disponible'}</small></span></div>; })}</div> : <p className="statistics-unknown">Sin jugadores registrados.</p>}</div>;
}
